### ISSUE TITLE
Train the model on my own traffic sign dataset using your pretrained weights

### ISSUE THREAD

**Issue by amardeepjaiman** [CJHMPower/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet#10]
Hi,

I have created my own dataset of traffic sign images. Could someone let me know how to train the model on my data using the author's pretrained weights ?

Thanks,
Amardeep

**Comment by CJHMPower** [comment]
First, you should understand the format of annotation json file used for this project. I use a dict to encode the categories and object location information and store it as a json file.
Second, modify parameters of RetinaNet to fit your dataset, such as the number of outputs, the size of anchors. 
Then you can download the pretrained weights and train your model described as the steps in README.

**Comment by amardeepjaiman** [comment]
Hi @CJHMPower , I have understood the annotation json format and i can convert my dataset into this format. Just wanted to understand, which command i should use to train the model using your pretrained weights.

python train.py -exp model

this command train the model from scratch but how to pass the pretrained model path in this command. I have also checked out the train.py but could not get how to load the pretrained model. Do i have to use resume option for this ?

Also i am also having images of 512x512 size should i also change the anchor size in this case ?

**Comment by CJHMPower** [comment]
Here is the code for resuming training on pretrained weights.
You just need to modify the path for weights and add a --resume argument in the training command.
<img width="700" alt="屏幕快照 2019-05-06 下午3 48 47" src="https://user-images.githubusercontent.com/25431724/57251182-2d6a2300-7017-11e9-8633-643288740ec8.png">

**Comment by amardeepjaiman** [comment]
Got it thanks @CJHMPower .

One more doubt i wanted to ask, whats the impact of image size on RetinaNet trainning and inferencing.

1. as my image size if 512x512, and By default Retinanet resize the training images to 800x1333 , does it necessary to do this upscaling for better results ? or this resizing is only required for large resolution images?

2. Is it necessary to have same size of images for inferencing which were used for training ? like if i had 512x512 images size for training then can i input any other size image directly for inferencing in RetinaNet ?

**Comment by CJHMPower** [comment]
No, the image size does not need to be the same. The size of input image will only influence the size of feature map.  But the pretrained weights are just weights of convolutional kernels and fully connected vectors. The parameters in my project are a little different from the original RetinaNet. I think they are well fit into image size of 512x512. No need to rescale again.

Good Luck!

**Comment by amardeepjaiman** [comment]
So if i understood correctly though i have trained my model on 512x512 imagery, i can do the predictions on 5000x5000 images or any other size using the trained model?

**Comment by CJHMPower** [comment]
Yes, you can.
