### ISSUE TITLE
training error "ValueError: u'po' is not in list"

### ISSUE THREAD

**Issue by amiltonwong** [CJHMPower/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet#12]
Hi, @CJHMPower ,

When I run the training script, I got the following error:

```
Preparing data..
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    image_ext=cfg.image_ext, classes=cfg.classes, encoder=DataEncoder(), transform=train_transform)
  File "/data/code9/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet/preprocessing/datasets.py", line 19, in __init__
    self.annotation_dir = AnnotationDir(annotation_file,classes)
  File "/data/code9/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet/preprocessing/annotations.py", line 11, in __init__
    self.ann_dict = self.build_annotations()
  File "/data/code9/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet/preprocessing/annotations.py", line 27, in build_annotations
    box = BoundingBox(left, top, right, bottom, cfg.width,cfg.height,self.labels.index(label))
ValueError: u'po' is not in list

```

It seems something wrong with the annotation file. I had downloaded the specified data.zip and extracted it into data/ folder. Could you give some hints to fix this issue?

THX!

**Comment by CJHMPower** [comment]
Hi, @
The 'po', 'io', 'wo' labels are not included in my training process, because I found them standing for 'None' objects(cannot be categoried as a specific traffic sign). That is the reason why I use 42 classes while the original TT100K uses 45 classes. You encountered this error possibly because you are using the original TT100K annotation file. Make sure you use the annotation files I created manually, whose names start with 'resnet'. 
Hope this will help, Good Luck!

**Comment by amiltonwong** [comment]
Hi, @CJHMPower ,

Thanks for your reply. In fact, I had downloaded [data.zip](https://pan.baidu.com/s/1u3S7fomkAywbTt43S5mKHg) which you specified. However, after unzip it, only `annotation.json`, train.zip and test.zip are found. According to [config.py](https://github.com/CJHMPower/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet/blob/master/config.py#L8), `annotation.json` is selected by default and it is my case. Moreover, [data/](https://github.com/CJHMPower/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet/tree/master/data) only contains several resnetXXX_predict.json and it seems they are not the ones you specified.

Where could I download the annotation files you specified?

THX!

**Comment by CJHMPower** [comment]
Hi, @amiltonwong 
This bug is due to the inconsistency of annotation file and class labels. I have committed a change on the code in annotation.py(line 22). It should skip the labels for ['po', 'io', 'wo']. Please try this out.

**Comment by amiltonwong** [comment]
Hi, @CJHMPower ,

Thanks a lot. It works now. :)
