### ISSUE TITLE
detect and classification is not well

### ISSUE THREAD

**Issue by Chrislzy1993** [CJHMPower/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet#14]
hi, @CJHMPower , thanks for your replaying, i can run in python2.7 env,  and i test sample pics, has no problem , but test my own data, traffic signs can not be detect and classification is wrong sometimes
![Figure_1-1](https://user-images.githubusercontent.com/17810965/69598520-8695b480-1044-11ea-8a47-43356dc6d33f.png)
![Figure_1-2](https://user-images.githubusercontent.com/17810965/69598609-d1173100-1044-11ea-9875-1dca1074ef74.png)
![Figure_1-4](https://user-images.githubusercontent.com/17810965/69598614-d4aab800-1044-11ea-9b7e-03254505454c.png)
and i test the pic include traffic signs, and the detect result is not good
![Figure_1-5](https://user-images.githubusercontent.com/17810965/69598637-f015c300-1044-11ea-85f2-7e37a7bd193c.png)
![Figure_1-3](https://user-images.githubusercontent.com/17810965/69598643-f4da7700-1044-11ea-826f-ee6f68de787a.png)
 i dont know where is wrong?

**Comment by Chrislzy1993** [comment]
i figure it out, it happens cause my input image size is 1200 X 1200, when resize, the traffic sign will be distort, Jagged(sorry for my sucked english), so the detection and classfication is not well, even bad.  finally, how should i do , when i input image is 1920X1200, if i use window slide, it will cause much time?? how should i do?? thank u again

**Comment by beimuyao** [comment]
Where did you download the pre-training model? The original link is invalid.Please.
