### ISSUE TITLE
Not able to access  the dataset provided for training in markdown file

### ISSUE THREAD

**Issue by KevinPatel04** [CJHMPower/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet#18]
https://pan.baidu.com/s/1u3S7fomkAywbTt43S5mKHg  (Not Working)

**Comment by CJHMPower** [comment]
The above link works only in Mainland China. Please try this link https://drive.google.com/file/d/1XOD_ML6QlO_t3Yk0rZ7PpQAOB761je0a/view?usp=sharing

**Comment by KevinPatel04** [comment]
Ok thank u 🤘
