### ISSUE TITLE
The datasets are abnormal

### ISSUE THREAD

**Issue by RexKing6** [CJHMPower/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet#3]
Hey, CJHMPower! Why the datasets that you provided are abnormal? Them seems like some time series data.

**Comment by amardeepjaiman** [comment]
yes, how to extract it ? same problem. any solution ?

**Comment by RexKing6** [comment]
Hey, if you are Chinese, you can download the true one from here, https://pan.baidu.com/s/1nYVCVQHKlJP4gv0twNZHMg, with BaiduYun. And the dataset is little big, I am uploading to the google dirve then give you later.

**Comment by RexKing6** [comment]
Here, https://drive.google.com/open?id=1MbLjUVCwpXa4VPx2fgQHkntCC2IyACXC, I close this issue now.
