### ISSUE TITLE
about cut picture

### ISSUE THREAD

**Issue by chi8411** [CJHMPower/Simultaneous-Traffic-Sign-Detection-and-Classification-with-RetinaNet#9]
How did you cut the size of 512*512 picture?
Thank you.

**Comment by CJHMPower** [comment]
The original images in TT100K are in size of 2048 x 2048. I cropped the origin images to 512x512 based on the annotated objects. That is, randomly selected a position(x,y) around the upper left corner of the object and cropped the new image as [x: x+512, y:y+512]. See 'evaluate/crop_image.ipynb' for details.
